Repository fhburgenland-bswe/ss2025-klimaatlas, pull requests merged in 2025-05, with the labels that each got.

#16 feat: add caching mechanism
  backend/src/main/java/at/big5health/klimaatlas/CacheConfig.java
  backend/src/main/java/at/big5health/klimaatlas/KlimaatlasApplication.java
  backend/src/main/java/at/big5health/klimaatlas/controllers/WeatherController.java
  backend/src/main/java/at/big5health/klimaatlas/grid/GridTemperature.java
  backend/src/main/java/at/big5health/klimaatlas/grid/GridUtil.java
  backend/src/main/java/at/big5health/klimaatlas/services/GridCacheService.java
  backend/src/main/java/at/big5health/klimaatlas/services/WeatherService.java
  backend/src/main/resources/application.properties
  backend/src/test/java/at/big5health/klimaatlas/GridCacheServiceIntegrationTest.java
  backend/src/test/java/at/big5health/klimaatlas/WeatherControllerTest.java
Labels: enhancement

#17 11 create a collapsible side panel for map information
  frontend/src/app/app.routes.ts
  frontend/src/app/layout/footer/footer.component.html
  frontend/src/app/layout/footer/footer.component.scss
  frontend/src/app/layout/footer/footer.component.spec.ts
  frontend/src/app/layout/footer/footer.component.ts
  frontend/src/app/layout/header/header.component.html
  frontend/src/app/layout/header/header.component.scss
  frontend/src/app/layout/header/header.component.ts
  frontend/src/app/layout/main/main.component.html
  frontend/src/app/layout/main/main.component.scss
  frontend/src/app/layout/main/main.component.spec.ts
  frontend/src/app/layout/main/main.component.ts
  frontend/src/app/layout/map/map.component.html
  frontend/src/app/layout/map/map.component.scss
  frontend/src/app/layout/map/map.component.spec.ts
  frontend/src/app/layout/map/map.component.ts
  frontend/src/app/layout/side-panel/pages/content/content.component.html
  frontend/src/app/layout/side-panel/pages/content/content.component.scss
  frontend/src/app/layout/side-panel/pages/content/content.component.spec.ts
  frontend/src/app/layout/side-panel/pages/content/content.component.ts
  frontend/src/app/layout/side-panel/pages/sources/sources.component.html
  frontend/src/app/layout/side-panel/pages/sources/sources.component.scss
  frontend/src/app/layout/side-panel/pages/sources/sources.component.spec.ts
  frontend/src/app/layout/side-panel/pages/sources/sources.component.ts
  frontend/src/app/layout/side-panel/side-panel.component.html
  frontend/src/app/layout/side-panel/side-panel.component.scss
  frontend/src/app/layout/side-panel/side-panel.component.spec.ts
  frontend/src/app/layout/side-panel/side-panel.component.ts
  frontend/src/app/pages/map/map.component.html
  frontend/src/app/pages/map/map.component.scss
  frontend/src/app/pages/map/map.component.spec.ts
  frontend/src/app/pages/map/map.component.ts
  frontend/src/app/services/map.service.spec.ts
  frontend/src/app/services/map.service.ts
Labels: enhancement

#19 feat: add sources page
  frontend/src/app/layout/map/map.component.spec.ts
  frontend/src/app/layout/map/map.component.ts
Labels: bug

#22 feat: add sources page
  frontend/src/app/layout/side-panel/pages/sources/sources.component.html
  frontend/src/app/layout/side-panel/pages/sources/sources.component.scss
  frontend/src/app/layout/side-panel/pages/sources/sources.component.ts
Labels: bug, documentation, enhancement

#32 docs: updated README, Architecture Diagram, and Swagger UI Integration
  .conform.yaml
  .idea/modules/klimaatlas.main.iml
  ArchitectureDiagram.jpg
  README.md
  backend/build.gradle
  backend/src/main/java/at/big5health/klimaatlas/controllers/MosquitoController.java
  backend/src/main/java/at/big5health/klimaatlas/controllers/WeatherController.java
Labels: documentation

#35 feat: add e2e tests
  .conform.yaml
  README.md
  frontend/e2e/admin-page.ts
  frontend/e2e/admin.spec.ts
  frontend/e2e/klimaatlas-page.ts
  frontend/e2e/klimaatlas.spec.ts
Labels: enhancement
